version: '3.8'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: etcd
    environment:
      - ETCD_AUTO_COMPACTION_RETENTION=1
      - ETCD_HEARTBEAT_INTERVAL=500
      - ETCD_ELECTION_TIMEOUT=10000
    # 2379: 클라이언트 통신
    # 2380: 피어 간 통신
    ports:
      - "2379:2379"
      - "2380:2380"
    command: [
      "etcd",
      "--listen-client-urls", "http://0.0.0.0:2379",
      "--advertise-client-urls", "http://etcd:2379",
      "--listen-peer-urls", "http://0.0.0.0:2380",
      "--initial-advertise-peer-urls", "http://etcd:2380",
      "--initial-cluster", "default=http://etcd:2380",
      "--initial-cluster-state", "new"
    ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2379/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  milvus:
    image: milvusdb/milvus:v2.3.0
    container_name: milvus
    # 19530: 서버 통신
    # 9091: 대시보드
    ports:
      - "19530:19530"
      - "9091:9091"
    command: ["milvus", "run", "mixture"]
    depends_on:
      - etcd
    environment:
    - ETCD_ENDPOINTS=http://etcd:2379

  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"     